name: "[M] UTBot Java: build and run tests"

on:
  workflow_dispatch
  
jobs:
  build-and-run-tests:
    runs-on: [self-hosted, blue]
    container: unittestbot/java-env:java11-zulu-jdk-fx-gradle7.4.2-kotlinc1.7.0
    steps:
    - uses: actions/checkout@v2
        
    - name: Build and run tests in UTBot Java
      run: |
        export KOTLIN_HOME="/usr"
        gradle clean build --no-daemon
        
    - name: Upload utbot-framework logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: utbot_framework_logs
        path: utbot-framework/logs/*
      
    - name: Upload utbot-framework tests report artifacts if tests have failed
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: utbot_framework_tests_report
        path: utbot-framework/build/reports/tests/test/*
        
    - name: Upload utbot-intellij tests report artifacts if tests have failed
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: utbot_intellij_tests_report
        path: utbot-intellij/build/reports/tests/test/*
